# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.thelastrow.lk" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Thelastrow.lk blog
  avatar: tlr_logo.jpg
  gravatar: # Email MD5 hash
  description: "Official blog of thelastrow.lk" # used by search engines

  # Header and footer text
  header_text:
  header_text_feature_image:
  footer_text: >
   <a href="https://www.thelastrow.lk">www.thelastrow.lk</a>

  # Icons
  rss: true
  email_address: "admin@thelastrow.lk"
  behance:
  bitbucket:
  dribbble:
  facebook: "https://www.facebook.com/thelastrow"
  flickr:
  github:
  google_plus:
  instagram:
  linkedin:  # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:  # Full URL
  steam:
  tumblr:
  twitter: "thelastrow"
  wordpress:
  youtube:

  # Scripts
  google_analytics: # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname:
  katex: false # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"
  
  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 10
paginate_path: "page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed
